api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 120

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

model:
  path: "models/fine_tuned/global_model.pth"